#!/bin/bash

#
# Copyright 2016, Yahoo Inc.
# Copyrights licensed under the New BSD License.
# See the accompanying LICENSE file for terms.
#

echo "Generating Documentation"
. $JMMHOME/jmm.sh
jmm doc github.com.jminusminus.core.Path > docs/core.Path.md
jmm doc github.com.jminusminus.core.Fs > docs/core.Fs.md
jmm doc github.com.jminusminus.core.http.Server > docs/http.Server.md
jmm doc github.com.jminusminus.core.http.IncomingMessage > docs/http.IncomingMessage.md
jmm doc github.com.jminusminus.core.http.OutgoingMessage > docs/http.OutgoingMessage.md
